repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npm --prefix front-end run format
        types_or: [javascript, jsx, ts, svelte]
        language: system
      # - id: eslint
      #   name: prettier
      #   entry: npm --prefix front-end run lint
      #   types_or: [javascript, jsx, ts, svelte, json]
      #   language: system
