create table "public"."notification_tokens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "token" text not null,
    "email" text not null
);

alter table "public"."notification_tokens" enable row level security;

CREATE UNIQUE INDEX notification_tokens_pkey ON public.notification_tokens USING btree (id);

CREATE UNIQUE INDEX notification_tokens_token_key ON public.notification_tokens USING btree (token);

alter table "public"."notification_tokens" add constraint "notification_tokens_pkey" PRIMARY KEY using index "notification_tokens_pkey";

alter table "public"."notification_tokens" add constraint "notification_tokens_email_fkey" FOREIGN KEY (email) REFERENCES users(email) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notification_tokens" validate constraint "notification_tokens_email_fkey";

alter table "public"."notification_tokens" add constraint "notification_tokens_token_key" UNIQUE using index "notification_tokens_token_key";

grant delete on table "public"."notification_tokens" to "anon";

grant insert on table "public"."notification_tokens" to "anon";

grant references on table "public"."notification_tokens" to "anon";

grant select on table "public"."notification_tokens" to "anon";

grant trigger on table "public"."notification_tokens" to "anon";

grant truncate on table "public"."notification_tokens" to "anon";

grant update on table "public"."notification_tokens" to "anon";

grant delete on table "public"."notification_tokens" to "authenticated";

grant insert on table "public"."notification_tokens" to "authenticated";

grant references on table "public"."notification_tokens" to "authenticated";

grant select on table "public"."notification_tokens" to "authenticated";

grant trigger on table "public"."notification_tokens" to "authenticated";

grant truncate on table "public"."notification_tokens" to "authenticated";

grant update on table "public"."notification_tokens" to "authenticated";

grant delete on table "public"."notification_tokens" to "service_role";

grant insert on table "public"."notification_tokens" to "service_role";

grant references on table "public"."notification_tokens" to "service_role";

grant select on table "public"."notification_tokens" to "service_role";

grant trigger on table "public"."notification_tokens" to "service_role";

grant truncate on table "public"."notification_tokens" to "service_role";

grant update on table "public"."notification_tokens" to "service_role";

