create table "public"."book_subscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ItemNo" text not null,
    "email" text not null
);


alter table "public"."book_subscriptions" enable row level security;

CREATE UNIQUE INDEX book_subscriptions_pkey ON public.book_subscriptions USING btree (id);

alter table "public"."book_subscriptions" add constraint "book_subscriptions_pkey" PRIMARY KEY using index "book_subscriptions_pkey";

alter table "public"."book_subscriptions" add constraint "book_subscriptions_ItemNo_fkey" FOREIGN KEY ("ItemNo") REFERENCES books_avail("ItemNo") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."book_subscriptions" validate constraint "book_subscriptions_ItemNo_fkey";

alter table "public"."book_subscriptions" add constraint "book_subscriptions_email_fkey" FOREIGN KEY (email) REFERENCES users(email) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."book_subscriptions" validate constraint "book_subscriptions_email_fkey";

grant delete on table "public"."book_subscriptions" to "anon";

grant insert on table "public"."book_subscriptions" to "anon";

grant references on table "public"."book_subscriptions" to "anon";

grant select on table "public"."book_subscriptions" to "anon";

grant trigger on table "public"."book_subscriptions" to "anon";

grant truncate on table "public"."book_subscriptions" to "anon";

grant update on table "public"."book_subscriptions" to "anon";

grant delete on table "public"."book_subscriptions" to "authenticated";

grant insert on table "public"."book_subscriptions" to "authenticated";

grant references on table "public"."book_subscriptions" to "authenticated";

grant select on table "public"."book_subscriptions" to "authenticated";

grant trigger on table "public"."book_subscriptions" to "authenticated";

grant truncate on table "public"."book_subscriptions" to "authenticated";

grant update on table "public"."book_subscriptions" to "authenticated";

grant delete on table "public"."book_subscriptions" to "service_role";

grant insert on table "public"."book_subscriptions" to "service_role";

grant references on table "public"."book_subscriptions" to "service_role";

grant select on table "public"."book_subscriptions" to "service_role";

grant trigger on table "public"."book_subscriptions" to "service_role";

grant truncate on table "public"."book_subscriptions" to "service_role";

grant update on table "public"."book_subscriptions" to "service_role";


