create table "public"."email_items" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "BID" bigint not null,
    "TitleName" text,
    "Author" text,
    "cover_url" text,
    "url" text,
    "BranchName" text[],
    "email" text
);


alter table "public"."email_items" enable row level security;

CREATE UNIQUE INDEX email_items_pkey ON public.email_items USING btree (id);

alter table "public"."email_items" add constraint "email_items_pkey" PRIMARY KEY using index "email_items_pkey";

alter table "public"."email_items" add constraint "email_items_email_fkey" FOREIGN KEY (email) REFERENCES users(email) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."email_items" validate constraint "email_items_email_fkey";

grant delete on table "public"."email_items" to "anon";

grant insert on table "public"."email_items" to "anon";

grant references on table "public"."email_items" to "anon";

grant select on table "public"."email_items" to "anon";

grant trigger on table "public"."email_items" to "anon";

grant truncate on table "public"."email_items" to "anon";

grant update on table "public"."email_items" to "anon";

grant delete on table "public"."email_items" to "authenticated";

grant insert on table "public"."email_items" to "authenticated";

grant references on table "public"."email_items" to "authenticated";

grant select on table "public"."email_items" to "authenticated";

grant trigger on table "public"."email_items" to "authenticated";

grant truncate on table "public"."email_items" to "authenticated";

grant update on table "public"."email_items" to "authenticated";

grant delete on table "public"."email_items" to "service_role";

grant insert on table "public"."email_items" to "service_role";

grant references on table "public"."email_items" to "service_role";

grant select on table "public"."email_items" to "service_role";

grant trigger on table "public"."email_items" to "service_role";

grant truncate on table "public"."email_items" to "service_role";

grant update on table "public"."email_items" to "service_role";


